### ISSUE TITLE
Поехала вёрстка в статье "Быстро и просто поднимаем свой DNS"

### ISSUE THREAD

**Issue by IvanUshakov** [podcast-uwp/p.umputun.com#2]
macOS 10.15.5, Google Chrome Версия 83.0.4103.116

<img width="2525" alt="Снимок экрана 2020-07-12 в 03 08 22" src="https://user-images.githubusercontent.com/485435/87235409-f34f9a80-c3ec-11ea-9ee8-9a4d386361b0.png">

**Comment by umputun** [comment]
да, подозреваю это результат https://github.com/podcast-uwp/p.umputun.com/pull/1

cc: @akellbl4
